# Generated by Django 4.2.8 on 2023-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('posicao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
    ]
